### PR TITLE
Update challenges section of messaging use case

### PR DESCRIPTION
**Pull request by creatornader**
***
<a href="https://pr-preview.s3.amazonaws.com/creatornader/did-use-cases/pull/132.html" title="Last updated on Dec 15, 2020, 5:40 PM UTC (5ce3560)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/132/6b93a8e...creatornader:5ce3560.html" title="Last updated on Dec 15, 2020, 5:40 PM UTC (5ce3560)">Diff</a>

### CODE REVIEW

**Review by philarcher — APPROVED** [review]
I remain concerned that this is putting the solution before the use case, and the new addition compounds that, but let's put this into the main PR and then Joe and I can review the complete thing.

**Comment by creatornader** [comment]
@philarcher I welcome any and all changes from the editors needed to get this across the line. If a particular bit is inappropriate we can remove or reword.

**Comment by jandrieu** [comment]
@philarcher I agree. In this PR in particular, the addition of DID Comm presents a solution-based on DIDs rather than a real-world value proposition that DIDs solve.

**Comment by creatornader** [comment]
I'm a bit confused. This is the *challenges* section. The only thing this PR does is call out that there may be a mitigant to the challenge presented in the first few sentences, but that even that mitigant has its own challenges.

**Comment by jandrieu** [comment]
DID Comm is a solution based on DIDs. As such, it isn't appropriate to use DID Comm itself to justify DIDs, because that would be tautological. 

This use case document is intended to illustrate real-world problems that can be solved if/when DIDs are fully realized. Since DID Comm doesn't exist if there aren't DIDs, including DID Comm here doesn't work.  On the other hand, we welcome illustrations of real-world problems that DID Comm can solve if/when DIDs are fully realized.

**Comment by creatornader** [comment]
This isn't about justifying DIDs though. It's talking about the real world problem of safely transitioning from out of band connections to secured connections, which still exists when DIDs are fully realized and can be partially but not completely solved by DIDComm and other DID-based messaging protocols (hence why it's listed under challenges). That literally fits into your definition of what's appropriate for this doc. Not willing to die on this hill in particular but that's how it fits.

**Pull request closed without merging**
