### PR TITLE
FPWD static ready

### PR DESCRIPTION
**Pull request by rhiaro**
* [x] DID WG respec meta
* [x] pubrules (except it can't find the patent policy text, which is there)
* [x] linkchecker
* [x] internal `/w3c-ccg/` links changed to `/w3c/`

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Nov 3, 2019, 7:15 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fdid-use-cases%2F7dd8eec50b0962607c2b094dfdb6050dfd5d0bf3%2Findex.html%3FisPreview%3Dtrue)

```
[33m📡 HTTP Error 520:[39m [36mhttps://rawcdn.githack.com/w3c/did-use-cases/7dd8eec50b0962607c2b094dfdb6050dfd5d0bf3/index.html[39m
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/did-use-cases%2324.)._
</details>

### CODE REVIEW

**Comment by iherman** [comment]
For some reasons the preview did not work. Here is a static view of the FPWD draft:

https://cdn.statically.io/gh/w3c/did-use-cases/fpwd/FPWD/2019-11-07/index.html

**Comment by iherman** [comment]
I am not sure about the reason why it complains about the patent policy thing, but I can settle that with the webmaster. Otherwise it looks o.k. to me. But:

- the WG has to agree on the final list of editors
- I do not think the November 7 date is tenable. The WG has to officially approve the publication, which puts this to Tuesday evening European time at the earliest, we have to ask for a FPWD approval and request publication through the webmaster. I think 12 of November is our first available publication date, provided the WG approves its publication tomorrow.

**Comment by rhiaro** [comment]
Yep, can update the date and editors when they're finalised.

**Comment by iherman** [comment]
One more thing (to be discussed with the WG): in the case of Notes, it is perfectly all right to publish a Note right away, and update the note as often as we want. In other words, the distinction between a 'Working Draft' and a 'Note' may be unnecessary. We can also set up (afaik) Echidna for a note, too, ie, making the note more or less a living document is perfectly possible. 

Food for thoughts.

**Comment by msporny** [comment]
> We can also set up (afaik) Echidna for a note, too, ie, making the note more or less a living document is perfectly possible.

+1 let's see if we can operate in that mode... it would result in the most up to date document being on TR as well as the least amount of (long term) fuss for the WG.

**Comment by iherman** [comment]
@msporny per https://github.com/w3c/echidna/wiki/How-to-use-Echidna#current-limitations the types of documents that can use Echidna are:

> only Candidate Recommendations, ordinary Working Drafts and ordinary Notes (no FPWD, FPWG-Note, LC, PR, or REC)

Ie, we would have to publish a FPWG-Note in a pedestrian way, (just like a FPWD for the spec) and then proceed with some sort of an Echida setup. No need to mix in the notion of a draft.

**Pull request merged**
