### PR TITLE
Psuedonymity not anonymity. Will fix Issue #111

### PR DESCRIPTION
**Pull request by philarcher**
Note, also updates main text for collecting payments for work conducted anonymously but left title in tact.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/pull/119.html" title="Last updated on Nov 2, 2020, 8:29 PM UTC (9ba557e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/119/9993275...9ba557e.html" title="Last updated on Nov 2, 2020, 8:29 PM UTC (9ba557e)">Diff</a>

### CODE REVIEW

**Comment by agropper** [comment]
I think this needs more work before it's ready to merge.

The relationship between anonymity and pseudonymity in a DID use-case
should not assume that readers share a common definition of the terms.
Comment
https://github.com/w3c/did-use-cases/issues/102#issuecomment-703943437
frames the issue of a relationship between anonymity and pseudonymity in
terms of governance or a "break the glass" cost. Another framing might be
in terms of Zero Knowledge Proofs issued in a governance context. Notaries
and mediators are other terms we have discussed that relate to this.

**Comment by philarcher** [comment]
Thank you @agropper. I'm outside my knowledge here so I defer to you and others of course. Personally, I was happy with anonymous. For the use case in question, each actor in the chain needs to know that other actors are authorized to have/have had/to take custody of a shipment. Information about *Who* they are is often not needed. It's about proving the chain, not who was in the chain. From my POV, therefore 'anonymous' is a perfectly acceptable term. I'm also anxious to avoid detailed solutineering in the UCR. @jandrieu - over to you to resolve this one.

**Comment by jandrieu** [comment]
@agropper We aren't trying to define psuedonymous or anonymous here, we just want to use the most appropriate term.

While I agree many will not know what pseudonymous means, *we* do, and IMO, we should use the right term.

**Review by jandrieu — APPROVED** [review]
This looks good. Pseudonymity is the more accurate term.

**Comment by philarcher** [comment]
Joe and I have discussed this and are minded to accept this change. @agropper, please raise a new issue or reopen the PR if you are unhappy with this action.

**Pull request merged**
