### PR TITLE
Adding UC/Req matrix

### PR DESCRIPTION
**Pull request by philarcher**
The first of several commits that will add specific Reqs for each use case and create a matrix table automatically.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/pull/92.html" title="Last updated on Aug 12, 2020, 1:37 PM UTC (c6702e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/92/983da09...c6702e3.html" title="Last updated on Aug 12, 2020, 1:37 PM UTC (c6702e3)">Diff</a>

### CODE REVIEW

**Comment by philarcher** [comment]
Don't look at this yet - I'm far from done. Just doing my laundry in public!

**Comment by philarcher** [comment]
OK, I need to work out how to make sure that the script is only called once, not twice, but you get the idea of what I'm trying to do here.

**Comment by jandrieu** [comment]
Well... the matrix is no longer a matrix...

**Comment by OR13** [comment]
@philarcher @jandrieu this is a pretty big PR, whats the status on it?

**Comment by philarcher** [comment]
I do not understand why the last commit to this PR doesn't work. I will have to investigate where in the copy and paste from the version I ave working perfectly in front of me, to this copy, the error came in. if I could see how to revert the last commit I'd do that :-( Really not having a good day today.

**Comment by philarcher** [comment]
OK, finally, I think I got it to work.

So this is ready for review now.

All the reqs and their definitions are in a data object. Each UC ends with a list of requirements that it entails. Each of those requirements is hyperlinked to their definition which is in a list after the requirements grid showing which reqs come from which UCs. Everything is written using the data object so the cross-linking works.

There is then the separate feature grid that, again, uses the same object to ensure consistency.

**Comment by philarcher** [comment]
Spoke too soon I was looking at my local copy that works perfectly, not the copy of the same thing - copy and paste, the same, that doesn't. I have no idea why.

**Comment by philarcher** [comment]
OK, so it sorta works OK now, except that my script runs twice, despite me putting in code I hoped would stop that happening. Need help to fix this. But, imagine the code didn't run twice...

**Comment by philarcher** [comment]
Thanks to @iherman, I've managed to get the scripting to run only once so that the cross references between UCs and reqs all work now as desired. This PR is therefore fully ready for review @jandrieu 

In terms of the substantive content, the key thing is to assess whether the reqs are indeed the right ones from each of the UCs. If not, I suggest this PR is merged and a future PR adjusts the relevant hooks in the text and, if needs be, the requirement definitions that are written exactly once in the JSON object.

**Review by jandrieu — APPROVED** [review]
This looks great!

**Pull request merged**
