### PR TITLE
Andrieu dhs use cases

### PR DESCRIPTION
**Pull request by jandrieu**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/pull/91.html" title="Last updated on Jul 15, 2020, 8:03 PM UTC (f966e62)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/91/3c0a21e...f966e62.html" title="Last updated on Jul 15, 2020, 8:03 PM UTC (f966e62)">Diff</a>

### CODE REVIEW

**Comment by davidlehn** [comment]
Full diff is large and unreadable.  I'd revert that big "fix merge issues" commit and try a rebase on master.

**Comment by jandrieu** [comment]
Thanks, @davidlehn I'm not sure how that happened, but I'll rebase as you suggest.

**Review by philarcher — APPROVED** [review]
No issue with the content. Some of the language would benefit from a tidy up, but basically this is good to go.

**Comment by jandrieu** [comment]
@philarcher This should be good to go. Merge if you like it.

**Comment by davidlehn** [comment]
Would be nice to squash out those giant merge commits, but not a huge deal.

**Comment by philarcher** [comment]
All good, thanks Joe. Merged and the branch deleted.

**Pull request merged**
