### PR TITLE
Echidna setup

### PR DESCRIPTION
**Pull request by iherman**
I have set up ECHIDNA following the same protocol as for did-core: every commit to master automatically creates a new document on www.w3.org/TR/

Beware with merging this: as soon as it is merged, ECHIDNA switches on...

### CODE REVIEW

**Review by rhiaro — APPROVED** [review]

**Review by deniak — APPROVED** [review]
I can't check if the token is the right one but the other parts are good

**Review by jandrieu — APPROVED** [review]
These configuration details are arcana to me. I'll trust @deniak and @iherman on this one.

**Review by philarcher — APPROVED** [review]
No problem for me, thank you!

**Comment by iherman** [comment]
> These configuration details are arcana to me. I'll trust @deniak and @iherman on this one.

Don't trust me, only @deniak :-)

Next time you guys commit, check whether the /TR has changed. It should. If not, we have to look into it...

**Comment by iherman** [comment]
Oops, I just realized you did! And 

https://www.w3.org/TR/did-use-cases/

is now dated 4th of December, which is what should be. Everything is o.k. then...

**Pull request merged**
