### PR TITLE
Add messaging focal use case (didcomm). Will fix issue #97

### PR DESCRIPTION
**Pull request by creatornader**
This is a replacement PR for the one opened by @OR13 [here](https://github.com/w3c/did-use-cases/pull/100), pinging DIDComm WG for others to review and give feedback.

***
<a href="https://pr-preview.s3.amazonaws.com/creatornader/did-use-cases/pull/122.html" title="Last updated on Dec 2, 2020, 11:03 PM UTC (e5c0dac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/122/3c122aa...creatornader:e5c0dac.html" title="Last updated on Dec 2, 2020, 11:03 PM UTC (e5c0dac)">Diff</a>

### CODE REVIEW

**Comment by philarcher** [comment]
Thank you @creatornader. I've made a few editorial changes to the doc since you wrote this so, to avoid merge problems, I have simply cloned your PR as a change from the updated file. @jandrieu and I are due to speak later today and, from my POV, your text, in PR 126, is ready to go.

Thanks again for this effort - much appreciated.

**Comment by creatornader** [comment]
@philarcher sounds great, thanks! I have a few subtle changes I was going to push to the PR this weekend after discussing with the DIDComm WG. Should I push those here or to your branch?

**Comment by philarcher** [comment]
Please push them to 'my' branch, @creatornader. Good job you reacted quickly - Joe and I were probably going to merge this in an hour's time. We'll wait until your done.

**Comment by philarcher** [comment]
Discussion moved to PR 126

**Pull request closed without merging**
