### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by davidlehn**
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/did-use-cases/pull/93.html" title="Last updated on Sep 2, 2020, 7:00 PM UTC (391bbed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-use-cases/93/8451f9c...davidlehn:391bbed.html" title="Last updated on Sep 2, 2020, 7:00 PM UTC (391bbed)">Diff</a>

### CODE REVIEW

**Review by philarcher — APPROVED** [review]
Thanks @davidlehn, sorry that this was necessary!

@jandrieu please go ahead and merge once you've checked

**Comment by OR13** [comment]
@jandrieu merge please :)

**Comment by davidlehn** [comment]
@jandrieu merge pretty please with sugar on top :)

**Comment by philarcher** [comment]
All being well, @jandrieu and I will be talking in a couple of hours' time and your wish will be granted @davidlehn

**Review by jandrieu — APPROVED** [review]
Good fixes. Will merge once I check for any conflicts.

**Pull request merged**
